adicionando pagina e testando endpoint people
alequeshow/desafio-balta-may-the-fourth-frontend pull request #15
Opened 2024-04-26 21:40 UTC by filipe-augusto

2024-04-26 23:07 UTC, alequeshow requested changes

2024-04-26 23:07 UTC, alequeshow commented on Starls.Assets/Starls.Assets.DTO/Character.cs
> +        public string Hair_Color { get; set; } = string.Empty;
As propriedades da classe DTO nao devem ser alteradas, a do gateway deve ser suficiente. O DTO tem que respeitar o contrato do desafio, que nao contem _.

Considerar isso nas outras implementações

2024-04-27 20:46 UTC, filipe-augusto commented on Starls.Assets/Starls.Assets.DTO/Character.cs
> +        public string Hair_Color { get; set; } = string.Empty;
fiz um novo commit com essa alteração

2024-04-28 18:28 UTC, gustavogonc approved these changes

2024-04-28 20:25 UTC, alequeshow commented on Starls.Assets/Starls.Assets.Presentation/Pages/Pessoas.razor
Renomear a pagina para People ou Characters

2024-04-28 20:32 UTC, alequeshow commented on Starls.Assets/Starls.Assets.Presentation/Pages/Pessoas.razor
> +﻿@page "/pessoas"
renomear rota para `/people` para mantermos a semantica do codigo em inglês

2024-04-29 22:13 UTC, alequeshow approved these changes

2024-04-30 01:03 UTC, gustavogonc approved these changes

2024-04-30 01:04 UTC, merged