consumo de endpoint de personagens
alequeshow/desafio-balta-may-the-fourth-frontend pull request #7
Opened 2024-04-24 23:45 UTC by filipe-augusto

2024-04-25 10:25 UTC, alequeshow requested changes

2024-04-25 10:25 UTC, alequeshow commented on Starls.Assets/Starls.Assets.Presentation/Program.cs
> -builder.Services.AddScoped<IFilmService, FilmService>();
Acho que um dos conflito esta nessa alteração. A FilmeService não deve ser removida

2024-04-25 10:25 UTC, alequeshow commented on Starls.Assets/Starls.Assets.Presentation/wwwroot/appsettings.json
> +    "Resource": "api/character/",
O endpoint na api é api/people/

2024-04-25 10:25 UTC, alequeshow commented on Starls.Assets/Starls.Assets.Service/Gateway/Extensions/FilmExtensions.cs
> +    internal static class CharacterExtensions
A classe errada foi renomeada. Compare o nome da classe com o nome do arquivo e vera que ficou invertido

2024-04-25 10:25 UTC, alequeshow commented on Starls.Assets/Starls.Assets.Service/Interfaces/ICharacterService.cs
> +        Task<IEnumerable<Character>> GetFilmsAsync();
Renomear o metodo para GetPeopleAsync

2024-04-25 18:11 UTC, filipe-augusto commented on Starls.Assets/Starls.Assets.Service/Interfaces/ICharacterService.cs
> +        Task<IEnumerable<Character>> GetFilmsAsync();
opa! vou manter getCaracter por enquanto, tudo bem? 
ou você prefere que eu mude tudo de caracter para people? 
ou somente esse metodo?

2024-04-26 00:43 UTC, alequeshow commented on Starls.Assets/Starls.Assets.Service/Interfaces/ICharacterService.cs
> +        Task<IEnumerable<Character>> GetFilmsAsync();
A ideia era fazer match com a classe, pois estava como Film ainda, tudo certo!

2024-04-26 01:01 UTC, alequeshow approved these changes

2024-04-26 02:16 UTC, merged